### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by goncy** [goncy/pency#1]
Actualmente la landing está vacía, necesitamos hacer algo que muestre la funcionalidad de Pency e invite a la gente a crear su tienda, podría tener algún formulario de contacto para crear la tienda

**Comment by LaggerP** [comment]
Holus. Tenes algún diseño ya ideado?

**Comment by goncy** [comment]
Voy a estar creando un figma / zeppelin en los proximos dias para iterar y lo comparto

**Comment by goncy** [comment]
https://www.figma.com/file/Y7AwjAIY2WTFAuHc5DqzeH/Pency?node-id=0%3A1 voy a ir subiendo todo aca

**Comment by VanessaPellegrini** [comment]
> https://www.figma.com/file/Y7AwjAIY2WTFAuHc5DqzeH/Pency?node-id=0%3A1 voy a ir subiendo todo aca

Te puedo ayudar con el diseño, esta va ser la paleta de colores que queres usar?

**Comment by joniko** [comment]
> https://www.figma.com/file/Y7AwjAIY2WTFAuHc5DqzeH/Pency?node-id=0%3A1 voy a ir subiendo todo aca

Mañana te armó algo. Déjame en ese file que querés decir, y si ya hay ejemplos Live

**Comment by goncy** [comment]
De una! Algunos demos son https://pency.now.sh/blondies y https://pency.now.sh/mima, gracias!

**Comment by goncy** [comment]
> > https://www.figma.com/file/Y7AwjAIY2WTFAuHc5DqzeH/Pency?node-id=0%3A1 voy a ir subiendo todo aca
> 
> Te puedo ayudar con el diseño, esta va ser la paleta de colores que queres usar?

Si @VanessaPellegrini !, esa misma, todos los colores en realidad salen de acá: https://chakra-ui.com/theme del color Cyan, los botones y todo serian de Chakra ya que esta cargado en el proyecto, lo que mas me interesa por que no me da el cerebro es una manera de mostrar lindos los features de la app (multi opcion, carrito, tarjetas, etc), las cosas que tiene la app en fin

**Comment by VanessaPellegrini** [comment]
Estan usando algún discord/slack para comunicarse?

**Comment by goncy** [comment]
> Estan usando algún discord/slack para comunicarse?

Sip, estamos en el de frontendcafe, aca te mando un invite, hablame cuando estes adentro que te agrego al canal de Pency! https://discord.gg/6kzUT8

**Comment by Itsjuanit** [comment]
https://www.figma.com/file/EXfJ7kiS2t3VTgpizeGmvp/Figma-por-pency?node-id=0%3A1 dejo esto por aca, tal vez sirve, seguro que hay muchas cosas por mejorar

**Comment by mateo2181** [comment]
@goncy como me puedo unir al discord? te puedo dar una mano para crear la tienda desde la landing.

**Comment by goncy** [comment]
@mateo2181 https://discord.gg/aRtk6F avisame cuando estas adentro que te agrego al rol de pency!

**Comment by mateo2181** [comment]
> @mateo2181 https://discord.gg/aRtk6F avisame cuando estas adentro que te agrego al rol de pency!

ya estoy dentro

**Comment by arielger** [comment]
Me puedo poner a trabajar en esto ✋

**Comment by goncy** [comment]
> > @mateo2181 https://discord.gg/aRtk6F avisame cuando estas adentro que te agrego al rol de pency!
> 
> ya estoy dentro

Hablame que no se cual sos jaja

**Comment by goncy** [comment]
Este es el figma que va by @joniko https://www.figma.com/file/ipxNlUq1rbzoTyuOLz0XKo/Pency.co?node-id=1%3A631 🙌

**Comment by goncy** [comment]
Esto lo tiene actualmente @lndgalante

**Comment by lndgalante** [comment]
Me quedan 2 secciones para terminar @goncy

**Comment by goncy** [comment]
Cerrada por @lndgalante
