### ISSUE TITLE
Agregar Nombre y Apellido pre envio de pedido

### ISSUE THREAD

**Issue by sbehrends** [goncy/pency#103]
Con el objetivo de reducir las preguntas posteriores en el pedido y cargar el resumen de pedido enviado por WhatsApp al sistema del local seria idea agregar pre checkout un paso con algunos datos personales, como Nombre y Apellido.

Pensando en una extension futura con otros medios de pago, etc, se me ocurre que el flujo de checkout tenga un segundo step.
Despues de la seleccion de preguntas, click en Continuar, donde se llenan algunos datos personas, y ahi si el envio del pedido a WhatsApp.

**Comment by goncy** [comment]
![image](https://user-images.githubusercontent.com/6494462/83152972-c9f4dc80-a0d4-11ea-852c-48c97215ff77.png)
Gracias! Tenemos esto en el roadmap, estamos esperando que se mergee el nuevo flow de cart y un cambio en el admin para entrarle a esto

**Comment by goncy** [comment]
@sbehrends closed on #106
