### ISSUE TITLE
Agregar accesibilidad a componentes de storybook

### ISSUE THREAD

**Issue by macravero** [goncy/pency#123]
Se podria agregar e implementar el [addon a11y](https://www.npmjs.com/package/@storybook/addon-a11y) de Storybook para testear la accesibilidad de los componentes en las stories.

**Comment by goncy** [comment]
De una @macravero , lo queres tomar?

**Comment by macravero** [comment]
Dale!

**Comment by macravero** [comment]
@goncy  tengo la branch local con esto ya, pero me di cuenta que no tengo permissions para pushear mi branch y armar el PR. Quizas se manejan diferente! Parti de DEV, aviso por las dudas!

Por otro lado, vi con el addon que hay ciertos problemas de accesibilidad en algunos componentes, y a storybook en general le faltan los docs. Creo que vi que hay mas issues abiertos de Storybook asi que quizas eso ya esta cubierto, pero estaria bueno discutir si interesa el esfuerzo de accesibilidad en los componentes y en cuyo caso, cuales son los esquemas graficos de la app (para modificar colores no contrastantes, etc).

En caso de querer armar stories respecto al ajuste de accessibilidad y la doc de storybook, no tengo drama en agregarlos tambien.

Por el tema de permisos y de que branch partir, si queres aclaramelo por aca y lo agrego al readme de yapa!

**Comment by goncy** [comment]
Excelente, cierro este issue y podemos crear otro para adaptar los colores, supuestamente todos los colores que usamos deberian ser accesibles ya que chakra tiene en cuenta eso, pero todo warning que te tire y que se pueda arreglar mandale nomas, en cuestiones de diseño tenemos el figma aca https://www.figma.com/file/ipxNlUq1rbzoTyuOLz0XKo/Pency.app?node-id=24%3A0&viewport=471%2C-641%2C1.5963261127471924 y cualquier duda le preguntamos a @joniko
