### ISSUE TITLE
[Presentacion] Hola, me encanta el proyecto.

### ISSUE THREAD

**Issue by nahuelcaceres** [goncy/pency#127]
Me gustaria sumarme en lo que sea que los pueda ayudar. Estoy dando mis primeros pasos en frontend y seria excelente ir viendo como trabajan en un proyecto real, aportar un granito de arena (ej: algun good first issue) y si fuera posible aprender.

**Comment by goncy** [comment]
Hola @nahuelcaceres de una! Creo que un good first issue son las traducciones, usamos una libreria para traducir el contenido y hay muchos lados en donde todavia estamos hardcodeando los strings y deberiamos usar el hook, esta hecho en varias partes de la app asi que seria medio investigar, copiar y pegar y de paso ver como anda todo, si te copa te explico mas y te asigno un issue

**Comment by nahuelcaceres** [comment]
Hola @goncy, muchisimas gracias. Si si, me encanta. Estaba mirando que utilizan i18n para esto, y vi algunos lugares donde no se utiliza, como mencionaste. Contame por donde crees que podria comenzar y si se puede, como seria el ciclo para integrar mis cambios via PR. Muchas gracias

**Comment by goncy** [comment]
En donde veas que hay strings planos podes meterlo, el flow es crearte un fork, levantar el proyecto y despues pull request desde el fork, si necesitas una mano avisa!

**Comment by nahuelcaceres** [comment]
Hola @goncy , no sabia si preguntarte aqui o via mail. Te voy a molestar un poco porque despues de chapotear bastante, no logro hacer una primer implementacion que seria en el componente app.screens.Landing.Features.tsx para utilizar la herramienta de traduccion.

En primer instancia  hago la importacion -->
` import {useTranslation} from "~/i18n/hooks";`

Sin entender muy bien el por que, hice la transformacion de la declarion de 

```
const Features = () => (
...
)
```

a lo siguiente (porque fue la unica manera en que encontre poder setear la constante t = useTranslation( );  )

```
const Features:React.FC = () => {
    const t = useTranslation();

    return (  

    )
}
```

Lo que no logro resolver es que me tome la funcionalidad y me cargue la traduccion
` {t("admin.preview")}`

Lo que hace es insertarme texto plano, digamos....veo en el componente "admin.preview"

No se si me explico.

Muchas gracias.
