### ISSUE TITLE
Problema con firebase credentials

### ISSUE THREAD

**Issue by sebanoe96** [goncy/pency#147]
Buenas, queria saber si alguno le paso esto:
![Sin título](https://user-images.githubusercontent.com/65458121/86395442-a34b3800-bc76-11ea-9246-faf5dc2b1b90.png)

El proyecto me funcionaba bien hace un tiempito, ahora entiendo que al hacer pull cambio la forma de cargar las variables de firebase relacionadas a la cuenta de servicio (las que estan en el json en firebase) y en vez de cargarlas en el .env.[ambiente].local ahora se tiene que usar la herramienta de encriptacion-decriptacion. En esa parte es donde creo que tengo el problema.
Sigo los pasos del Readme (mode CBC,Key Size, etc), le doy a Encrypt y ese output lo pego en  firebase\credentials.ts.

Ese output, ¿Se debe pegar reemplazando los caracteres que ya existen dentro de return decrypt(`...`); ? Eso es lo que estoy haciendo ahora.

Depues de hacer esto hago el npm run dev y me tira el error que puse arriba en la captura de pantalla.
Alguna idea? Gracias!!

**Comment by goncy** [comment]
Buenas, imagino que debe ser algo mal copiado, te recomiendo generar una nueva service account y directamente subir el archivo a la herramienta de encrypt

**Comment by facuesr** [comment]
Buenas, me paso lo mismo y lo que me faltaba era configurar la key env en el archivo env.development.local. 

![image](https://user-images.githubusercontent.com/29279815/86623975-ea983800-bf98-11ea-8044-249987965442.png)

**Comment by sebanoe96** [comment]
Hola gente, mil disculpas que no contesté antes, estuve complicado con otros temas.
Voy a probar eso @facuesr y aviso, lo veo posible! Gracias a ambos

**Comment by sebanoe96** [comment]
Ahi pude probar y efectivamente era lo que decia Facu!

Gracias gente y perdón las molestias
