### ISSUE TITLE
Login administrador de tienda

### ISSUE THREAD

**Issue by LaggerP** [goncy/pency#15]
Modificar el actual login de administrador de tienda.

Que el Login por defecto sea el siguiente:

- Desktop:

![image](https://user-images.githubusercontent.com/29312124/80926727-61ce0780-8d6f-11ea-9eb0-82094246d0a0.png)

- Mobile:
![image](https://user-images.githubusercontent.com/29312124/80926544-5f1ee280-8d6e-11ea-93a6-c2c67f5260ac.png)

Es posible también hacer que:

- los colores cambien según la configuración de color del _Panel de administración_ que haga el administrador de la tienda.

- Se asigne la imagen de la tienda como imagen de login

![image](https://user-images.githubusercontent.com/29312124/80926707-45ca6600-8d6f-11ea-92ca-c41cd435f35d.png)

![image](https://user-images.githubusercontent.com/29312124/80926712-4ebb3780-8d6f-11ea-868f-2e0df1a66357.png)

[_Figma del diseño propuesto_](https://www.figma.com/file/4N98O1nwrTDWDEMv0TWfrO/Login-admin-pency?node-id=0%3A1)

**Comment by arielger** [comment]
Esta este diseño disponible también: https://www.figma.com/file/ipxNlUq1rbzoTyuOLz0XKo/Pency.co?node-id=7%3A0

Si se va a implementar la landing page de ese figma estaria bueno mantener la consistencia de estilos.

**Comment by goncy** [comment]
Fixed in #50
