### ISSUE TITLE
Arreglar width en carousel de imagenes

### ISSUE THREAD

**Issue by goncy** [goncy/pency#164]
![image](https://user-images.githubusercontent.com/6494462/88427225-e6f21700-cdc8-11ea-8d29-4e85a76e1b46.png)

En mobile (mobile real no simulando mobile en desktop) algunas veces se rompen las cards del carousel de destacados, pasa principalmente en cards con titulos muy largos

**Comment by CristianCucunuba** [comment]
El layout del card se rompe en cualquier dispositivo cuando tiene una palabra muy larga.

**Desktop**:
![image](https://user-images.githubusercontent.com/8785633/88471220-189fd680-cecc-11ea-9764-ac07e480c001.png)

Tambien pasa en otros lugares donde se utilice el titulo del producto, como en el `CartDrawer` y en el `CartSummaryDrawer`

**Comment by goncy** [comment]
@CristianCucunuba gracias por el PR! Evidentemente lo que decis es un bug, pero me parece que es diferente por que el otro pasa solo en mobile y no depende de tener palabras largas, pero ojalá se solucione con esto 🙌

**Comment by goncy** [comment]
@CristianCucunuba vuelvo a abrir este por que confirmo que sigue roto, lo probe en ios, desde el browser de instagram con https://pency.app/ilpradolibreria y sigue pasando, voy a ver si lo puedo reproducir en local a ver si le puedo sacar la vuelta

**Comment by goncy** [comment]
Solucionado! Se pushea mañana
