### ISSUE TITLE
Nombres legibles para los ids de orden

### ISSUE THREAD

**Issue by goncy** [goncy/pency#165]
![image](https://user-images.githubusercontent.com/6494462/88427432-451efa00-cdc9-11ea-9650-456340108740.png)

Los nombres de orden no son legibles, estaria bueno podes hacer algo al menos un poco mas legible, por ejemplo, para el slug `goncy` generar un numero de orden: `GON-A34S3`

**Comment by matias4205** [comment]
Yo lo tomo
