### ISSUE TITLE
Selección de color - Panel de administración

### ISSUE THREAD

**Issue by LaggerP** [goncy/pency#17]
El actual seleccionador de color no es muy amigable y tampoco tan visual.

_Actual seleccionador:_

![image](https://user-images.githubusercontent.com/29312124/80929345-89c66680-8d81-11ea-8535-923fb0ecd179.png)

**Estaría bueno implementar un nuevo diseño que muestre los colores para seleccionar**

_Seleccionador propuesto:_

![image](https://user-images.githubusercontent.com/29312124/80929340-7adfb400-8d81-11ea-8571-4444d50547b3.png)

- _La idea es que los colores de los cuadritos cambien la intensidad cada vez que el usuario seleccione una intensidad... Esto le permitiría ver el color que desea sin tener que guardar constantemente hasta encontrar el que le guste._
- _Otra opción es que el **navbar** modifique su color en tiempo real cada vez que el administrador de la tienda cambie el color e intensidad antes de guardar._

El color seleccionado estaría con una "sombra" dando a saber que ese es el color seleccionado actual. 

> En la imagen de ejemplo el color que se usa de sombra es el mismo que colorea la tab Tienda (#C4F1F9)
> ![image](https://user-images.githubusercontent.com/29312124/80929365-bda18c00-8d81-11ea-926d-776e00f1f322.png)

Cambio explicado en el siguiente [figma](https://www.figma.com/file/EwHvs9FhD9qTG1Zay0SzdJ/Color-panel-de-adminstraci%C3%B3n?node-id=0%3A1)

**Comment by goncy** [comment]
Me gusta, al backlog de una

**Comment by jnfrati** [comment]
Buenas! Alguien se esta encargando de este Issue?

**Comment by goncy** [comment]
@jnfrati no nadie!

**Comment by goncy** [comment]
Cerrado en #46
