### ISSUE TITLE
[Tienda] Nuevo formato para mostrar items v1

### ISSUE THREAD

**Issue by joniko** [goncy/pency#30]
<img width="1280" alt="Desktop" src="https://user-images.githubusercontent.com/1271235/81244426-d2338d80-8fe8-11ea-9630-f3815d8bd1cb.png">
<img width="360" alt="Mobile" src="https://user-images.githubusercontent.com/1271235/81244440-da8bc880-8fe8-11ea-93f6-7e5d1270763d.png">

<img width="360" alt="rows" src="https://user-images.githubusercontent.com/1271235/81242640-08224300-8fe4-11ea-8bfd-e22c0d3ec6cb.png">

Margenes laterales 16px
Margenes superior en inferior 24px

**Comment by goncy** [comment]
Excelente, @joniko como manejamos el add to cart?

**Comment by arielger** [comment]
Estoy trabajando en esto 🤚

**Comment by goncy** [comment]
Close approach cerrado en #128
