### ISSUE TITLE
Nuevo header para tiendas

### ISSUE THREAD

**Issue by joniko** [goncy/pency#36]
<img width="1044" alt="Screen Shot 2020-05-08 at 1 23 38 AM" src="https://user-images.githubusercontent.com/1271235/81370056-9113aa00-90ca-11ea-8b43-3389725e417e.png">

**Comment by goncy** [comment]
Buenisimo, ademas podemos usar la imagen de banner, titulo y descripcion que tenemos hoy en dia

**Comment by goncy** [comment]
Cerrado en #39
