### ISSUE TITLE
[Tienda] Nueva barra de Categorias y Search

### ISSUE THREAD

**Issue by joniko** [goncy/pency#37]
<img width="1244" alt="Screen Shot 2020-05-08 at 1 24 36 AM" src="https://user-images.githubusercontent.com/1271235/81370115-b4d6f000-90ca-11ea-83cf-43964b001b1d.png">

**Comment by goncy** [comment]
Como se comportaria en mobile cuando tocamos los botones de search @joniko ?

**Comment by joniko** [comment]
@goncy está en el archivo Figma el resto.

**Comment by goncy** [comment]
Implementado
