### ISSUE TITLE
Manejar mensajes de error de firebase

### ISSUE THREAD

**Issue by OscarVelandia** [goncy/pency#41]
En este momento cuando se hace POST a la ruta de creación de la tienda `http://localhost:3000/api/tenant?slug=NOMBRE_DE_TU_TIENDA` y hay algún error de autenticacion en firebase, el mensaje de la respuesta es "undefined" y el mensaje de error es 500. 

Un ejemplo de respuesta cuando el password no tiene el formato requerido es:
```
errorInfo: {
    code: 'auth/invalid-password',
    message: 'The password must be a string with at least 6 characters.'
  }
```

**Comment by goncy** [comment]
Cerrado en #42
