### ISSUE TITLE
[Admin] Nuevo estilo para el listado de productos

### ISSUE THREAD

**Issue by joniko** [goncy/pency#49]
<img width="505" alt="Screen Shot 2020-05-10 at 10 19 53 PM" src="https://user-images.githubusercontent.com/1271235/81515885-6a44b600-930c-11ea-9599-5d289937fb31.png">
<img width="1350" alt="Screen Shot 2020-05-10 at 10 19 47 PM" src="https://user-images.githubusercontent.com/1271235/81515892-6d3fa680-930c-11ea-96a4-1dc7531c6533.png">

Aún estoy en duda si mantener listados por cada categoria,  y si mantener el link clonar en mobile.

**Comment by goncy** [comment]
Listo hace tiempo, olvide cerrarlo
