### ISSUE TITLE
[Tienda] Cambiar texto en el botón de pedido

### ISSUE THREAD

**Issue by joniko** [goncy/pency#70]
Cambiar el texto del botón en el cart que diga: "**Completar pedido en WhatsApp**" usando el color verde de WhatsApp.

**Comment by LaggerP** [comment]
no queda muy lindo que digamos
![image](https://user-images.githubusercontent.com/29312124/81977204-0c5fe900-9600-11ea-9879-11ead08d99c8.png)


Asi no quedaria mejor?
![image](https://user-images.githubusercontent.com/29312124/81977315-374a3d00-9600-11ea-985e-dc310ba03ded.png)

**Comment by joniko** [comment]
Esta perfecto la 2da opcion, a esa me refería

**Comment by goncy** [comment]
Fixed en #74
