### ISSUE TITLE
[Tienda] Permitir al usuario elegír un color personalizado para su tienda. 

### ISSUE THREAD

**Issue by joniko** [goncy/pency#79]
Deberiamos sumar alguna explicación sobre contraste y contemplar su aplicación mobile.

**Comment by goncy** [comment]
Creo que este va a ser un won't fix por un largo tiempo por que tendriamos que generar un pallette accesible, si bien no seria muuy complicado de hacer es algo que tenemos que ver bien, lo voy a mover a low hasta que lo podamos decidir bien

**Comment by goncy** [comment]
Voy a cerrar esto hasta que lo necesitemos
