### ISSUE TITLE
No puedo crear una tienda

### ISSUE THREAD

**Issue by sebanoe96** [goncy/pency#80]
Queria probar crear una tienda pero cuando en postman hago el post en consola me tira esto:

RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined

Me lleva a la linea 147:
   return await this.run(req, res, parsedUrl);

en next-server.js

Alguna idea?
Gracias!

**Comment by goncy** [comment]
Estas seguro de que todas las variables en el .env.development estan bien cargadas? Pusiste console.logs para debuggear que pasaba?

**Comment by dieduro** [comment]
Hola Seba. Yo al principio me encontre con un error similar. 
Era que las variables de entorno no se estaban levantando bien. Necesitaba renombrar el .env a .env.development -siempre y cuando estés levantando el proyecto con `yarn dev` o `npm run dev`.
Para ver si las variables están llegando bien podés tirar un `console.log(process.env)`en next.config.js antes de `module.exports`.

**Comment by sebanoe96** [comment]
Hola, gracias a los dos por responder.
Hice ese console.log de process.env y las variables en .env.development las está tomando bien.
Y si, estoy usando npm run dev.

El private key de Firebase lo paso por la funcion btoa del browser tal cual viene en el json (pensé que capaz era eso).

Probé en dos computadoras distintas, por las dudas, pero en las dos tira lo mismo.
Al codigo no lo modifique, simplemente clone el repo y complete las variables (el localhost:3000 funciona)

Hice console.log del parsedUrl y viene bien el slug que mando en el post

**Comment by sebanoe96** [comment]
Ahi cuando npm run dev funciona bien

![image](https://user-images.githubusercontent.com/65458121/82160122-78915580-9869-11ea-8ea1-9bb95baa2c2a.png)

Ahora cuando hago el POST:

![image](https://user-images.githubusercontent.com/65458121/82160136-9363ca00-9869-11ea-8ab4-3d322de2fbbf.png)

(Es un 500 Internal Server Error)

**Comment by dieduro** [comment]
Seba, chequeaste tener habilitado "Correo electrónico/contraseña" como Sign-in method?
Eso está en Authentication > Sign-in method.

**Comment by sbehrends** [comment]
Habilitar "Correo electrónico/contraseña" es un paso que creo que no esta en el `README.md`. En mi caso fue lo que me falto para poder hacer el login

**Comment by dieduro** [comment]
Sí, tenés razón Sergio. De hecho cuando lo charlé con Goncy me dijo si podía hacer una PR y cuando la hice, justo ese paso no lo agregué. :sweat_smile:

**Comment by goncy** [comment]
Datazo, 3 personas es un monton, lo voy a agregar, perdon y gracias!

**Comment by sebanoe96** [comment]
Si, lo tenia habilitado ese sign in. Lo lei varias veces al readme para asegurarme que no me falte ningun paso, pero no hubo suerte jaja.
La base de datos de Firebase se crea sola supuestamente no?
Yo el firestore.rules no lo toque para nada

**Comment by sebanoe96** [comment]
Bueno gente, no me pregunten por qué pero probe con una cuenta vieja que tenia de Firebase con otro email y ahora funcionó. La verdad ni idea jajaa. Muchisimas gracias a todos por la ayuda y ojala pueda ayudar en algo!

**Comment by sebanoe96** [comment]
Obviamente si creo algo (vendo ropa) todos los créditos para vos @goncy y te aviso!

**Comment by goncy** [comment]
Gracias @sebanoe96 ! la db no se crea sola, tenes que ir a la pestaña firestore en firebase y habilitarla, despues vas a `rules` y tenes que pegar el contenido del archivo firestore.rules!
