### ISSUE TITLE
[Tienda] Sumar un campo para que el usuario especifique una dirección de envío

### ISSUE THREAD

**Issue by LucioB16** [goncy/pency#85]
Agregar un campo en el checkout para que el usuario pueda escribir adonde quieren que le manden su compra, esto me imagino sería algo que el admin de la tienda puede habilitar o deshabilitar.

Lo mismo se podría hacer para que el usuario elija un medio de pago (Efectivo | Tarjeta), y en caso de que elija efectivo que especifique con cuánto pagaría.

![image](https://user-images.githubusercontent.com/38698067/82392721-f8aaed00-9a1a-11ea-9c07-ef66ce69c1b5.png)

**Comment by goncy** [comment]
No seria algo que vayamos a implementar, por lo menos en el corto plazo, ya que no todas las tiendas envian ni aceptan metodos de pago fijos, la app por ahora solamente se encarga de nexo entre el catalogo y el cliente
