### ISSUE TITLE
[Admin] Updates y novedades de la tienda

### ISSUE THREAD

**Issue by dieduro** [goncy/pency#90]
Estaba pensando que tal vez podría estar bueno publicar novedades, nuevas features, noticias en la sección Admin para que las tiendas puedan estar al tanto de los avances de Pency. Podría ser en una tab como lo son Productos y Tienda.

**Comment by goncy** [comment]
Estaria bueno agregar una seccion de changelog en las nuevas secciones que estan pactadas en el figma, +1 para mi

**Comment by goncy** [comment]
Basico pero se implemento
