### ISSUE TITLE
Mover codigo de Sentry a su propio modulo

### ISSUE THREAD

**Issue by goncy** [goncy/pency#96]
Exponiendo los metodos y checks que usamos con una api amigable por si algun dia cambiamos de servicio

**Comment by joelalejandro** [comment]
@goncy Se puede armar un servicio de captura de errores que puedas inicializar con un Provider que maneje las particularidades del proveedor de error.

Feliz de armarlo si sirve ^_^

**Comment by goncy** [comment]
@joelalejandro perfecto, si la idea era crear un modulo en el proyecto (al igual que analytics, i18n o alguno de los que ya esta) llamado reporting que abstraiga la api de sentry y exponga una api onda reporting.report o eso, para tenerlo ordenado, si te va de una! Avisamr nomas

**Comment by joelalejandro** [comment]
Dale que va, me lo llevo yo

**Comment by joelalejandro** [comment]
@goncy Ahí te dejé el PR #139 con mi implementación. Avisame cualquier cosa 🤘
